nodejs:
  version: '14.15.1'
  url: 'https://nodejs.org/dist/v14.15.1/node-v14.15.1-linux-x64.tar.xz'

nativefier:
  version: '42.0.2'

electron:
  version: '11.0.3'

electron-wvvmp:
  version: '11.0.3'
